/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRow: typeof import('element-plus/es')['ElRow']
    LDA: typeof import('./src/components/LDA.vue')['default']
    LinksTrend: typeof import('./src/components/LinksTrend.vue')['default']
    Map: typeof import('./src/components/map.vue')['default']
    SentimentTrend: typeof import('./src/components/SentimentTrend.vue')['default']
    Template: typeof import('./src/components/template.vue')['default']
    Top: typeof import('./src/components/Top.vue')['default']
    Top10: typeof import('./src/components/Top10.vue')['default']
  }
}
